version: '3'

services:

  nginx:
    image: nginx
    deploy:
      placement:
        constraints:
          - node.hostname == docker1
      mode: replicated
      replicas: 3
    ports:
      - "8181:8181"
    networks:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - clientapp

  clientapp:
    image: fullmetalcloud/clientapp
    build:
      context: ./client/
      dockerfile: ./Dockerfile-client
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - backend
      - frontend
    ports:
      - "5000"
    depends_on:
      - serverapp

  serverapp:
    image: fullmetalcloud/serverapp
    build:
      context: ./server/
      dockerfile: ./Dockerfile-server
    networks:
      - backend
      - frontend
    ports:
      - "8282:8282"
    depends_on:
      - redis-master
      - redis-slave

  redis-master:
    image: redis:4.0.8
    ports:
      - "6379:6379"
    networks:
      - backend

  redis-slave:
    image: redis:4.0.8
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6380:6379"
    networks:
      - backend
    depends_on:
      - redis-master

  

networks:
  frontend:
  backend: